usgs/earthquake-eventadmin

src/htdocs/css/index.scss
src/htdocs/js/ChooseEventView.js

Lets the user search 15 min around a entered time and checks to make sure entered time is valid.

Latesteq 325

---

src/htdocs/modules/admin/AdminSummaryDetailsPage.js
src/htdocs/modules/admin/SendProductView.js

the delete product view was already handled by SendProductView, this PR allows for additional header and helper text customization for the different actions.

LATESTEQ 338

---

src/htdocs/css/event.scss
src/htdocs/modules/admin/EventComparisonView.js

Highlight the current event in the EventsNearbyView and the EventsAssociatedView

LATESTEQ-354

---

src/htdocs/event.php
src/htdocs/modules/admin/AdminSummaryPage.js
src/htdocs/modules/admin/AssociateEventView.js
src/htdocs/modules/admin/EventsNearbyView.js
src/lib/configure.inc.php

LATESTEQ-337

---

src/htdocs/event.php
src/htdocs/index.php

$SEARCH_STUB was never being set, fixed.
Also, update code that references config variable that no longer exists.

Fix search url

---

src/htdocs/modules/admin/summary/SummaryPage.js

Opens link view in modal dialog for add/edit subclass general summary page.

added getLinks, getLink and getAddLinkClick to general summary page

---

src/htdocs/modules/admin/EditLinkView.js

added title for modal dialog box

---

src/htdocs/js/CatalogEvent.js
src/htdocs/modules/admin/AdminEventModulePage.js
src/htdocs/modules/admin/AdminSummaryDetailsPage.js
src/htdocs/modules/admin/EventComparisonView.js
src/htdocs/modules/admin/ProductHistoryView.js
src/htdocs/modules/admin/_ProductHistoryView.scss
src/htdocs/modules/admin/scientific/ScientificSummaryPage.js
src/htdocs/modules/admin/summary/SummaryPage.js
src/htdocs/modules/admin/summary/_SummaryPage.scss
src/htdocs/modules/admin/summary/index.scss

Depends on these changes to event pages:
https://github.com/usgs/earthquake-eventpages/pull/197

Handle deleted events

---

src/htdocs/modules/admin/AdminModule.js
src/htdocs/modules/admin/AllProductsPage.js
src/htdocs/modules/admin/_AllProductsPage.scss
src/htdocs/modules/admin/index.scss

Add a page that displays product actions for all non-superseded products

AllProductsPage

---

src/htdocs/js/CatalogEvent.js
src/htdocs/modules/admin/AssociateEventView.js
src/htdocs/modules/admin/_AssociateEventView.scss
src/htdocs/modules/admin/index.scss

AssociateEventView was broken, associate products could not be sent.

AssociateEventView Fix

---

.travis.yml
package.json
src/htdocs/event.php
src/htdocs/modules/admin/AssociateEventView.js
src/lib/configure.inc.php
src/lib/pre-install.php

Fixes #47 , by sending and additional associate product when there are 2 ids from the same source preventing association but the preferred ids are not from the same source.

Patched eventpages

---

package.json

updated to use correct hazdev-cache-invalidator dependency

---

src/htdocs/css/_Login.scss
src/htdocs/css/index.scss
src/htdocs/login.php

Create simple login form. Form displays "error" param.

---

src/htdocs/modules/admin/ProductActionsView.js

changed button text to Make Authoritative

---

src/lib/configure.inc.php
src/lib/install/DatabaseInstaller.class.php
src/lib/install/MysqlDatabaseInstaller.class.php
src/lib/pre-install.php
src/lib/setup_database.php

This assumes that the session database and read/write user already exist.
fixes #64

Update installation for authentication

---

etc/events/us10004u1y.json
gruntconfig/connect.js
src/htdocs/css/event.scss
src/htdocs/js/admin/CatalogEvent.js
src/htdocs/js/admin/EventComparisonView.js
src/htdocs/js/admin/EventsAssociatedView.js
src/htdocs/js/admin/ProductFactory.js
test/spec/EventsAssociatedViewTest.js
test/test.js

added make authoritative button to summary page

---

src/htdocs/js/admin/AdminSummaryPage.js

commented out invalidate button and eventListener etc

---

src/htdocs/_navigation.inc.php

added Latest earthquakes link to side nav

---

src/htdocs/css/_ContentsManagerView.scss
src/htdocs/css/addedit.scss
src/htdocs/js/admin/AddEditPage.js
src/htdocs/js/admin/ContentsManagerView.js
test/spec/ContentsManagerViewTest.js
test/test.js

Add a General Header

---

src/htdocs/js/admin/AddEditPage.js

removed widget product pin and changed order of pins

---

src/lib/setup_database.php

Prompt for admin credentials while installing the session table

---

src/htdocs/js/admin/AddEditPage.js

unbind addGeneralHeaderButton in destroy

---

src/htdocs/js/admin/AdminSummaryPage.js

added a modal view that warns the user about deleteing events

---

src/htdocs/js/admin/AddEditPage.js

If general-header exists, use that product

---

src/htdocs/js/admin/AssociateEventView.js

Hide associate dialog after sending associate product

---

src/htdocs/js/admin/ContentsManagerView.js
test/spec/ContentsManagerViewTest.js

fixes #107
This helps with presentation on the event pages.

Use paragraph tag to wrap header text

---

src/htdocs/js/admin/ContentsManagerView.js

fixes #113 
If you have any thoughts on the text or where we link to first on the template, feel free to make a suggestion.

Update general-text view to include link to earthquake theme

---

src/htdocs/css/_EventComparisonView.scss
src/htdocs/css/event.scss
src/htdocs/js/admin/EventComparisonView.js

fixes #125
Add "Make Authoritative" button to the preferred origin in the associated events table.

Add "Make Authoritative" button 
